version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    volumes:
      # DOCKER VOLUME
      - "./basedatos:/var/lib/mysql"
  app:
    image: app:latest
    ports:
       - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
       - docker-mysql